# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  promtail.yml: |
    scrape_configs:
    - job_name: otel
      pipeline_stages:
      - cri: {}
      - json:
          expressions:
            timestamp: time
      - timestamp:
          format: RFC3339Nano
          source: timestamp
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_pod_label_name
        target_label: __service__
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: keep
        regex: ^landlordcachesrv$
        source_labels:
        - __meta_kubernetes_pod_container_name
      - action: replace
        source_labels:
        -  __meta_kubernetes_pod_label_app_kubernetes_io_name
        target_label: app
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_label_app_kubernetes_io_version
        target_label: version
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"promtail.yml":"scrape_configs:\n- job_name: otel\n  pipeline_stages:\n  - cri: {}\n  - json:\n      expressions:\n        timestamp: time\n  - timestamp:\n      format: RFC3339Nano\n      source: timestamp\n  kubernetes_sd_configs:\n  - role: pod\n  relabel_configs:\n  - source_labels:\n    - __meta_kubernetes_pod_label_name\n    target_label: __service__\n  - source_labels:\n    - __meta_kubernetes_pod_node_name\n    target_label: __host__\n  - action: keep\n    regex: ^landlordcachesrv$\n    source_labels:\n    - __meta_kubernetes_pod_container_name\n  - action: replace\n    source_labels:\n    -  __meta_kubernetes_pod_label_app_kubernetes_io_name\n    target_label: app\n  - action: replace\n    source_labels:\n    - __meta_kubernetes_pod_name\n    target_label: pod\n  - action: replace\n    source_labels:\n    - __meta_kubernetes_pod_container_name\n    target_label: container\n  - action: replace\n    source_labels:\n    - __meta_kubernetes_pod_label_app_kubernetes_io_version\n    target_label: version\n  - replacement: /var/log/pods/*$1/*.log\n    separator: /\n    source_labels:\n    - __meta_kubernetes_pod_uid\n    - __meta_kubernetes_pod_container_name\n    target_label: __path__\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"promtail","namespace":"monitoring"}}
  creationTimestamp: "2023-08-24T06:38:39Z"
  name: promtail
  namespace: monitoring
  resourceVersion: "802910783"
  uid: 099d2df3-9ad2-46fe-b797-7f011e1d0852

