#!/bin/bash

_step_cli_bash_autocomplete() {
    local cur="${COMP_WORDS[COMP_CWORD]}"
    local opts

    opts=$("${COMP_WORDS[@]:0:$COMP_CWORD}" "${cur:+$cur }--generate-bash-completion")

    COMPREPLY=($(compgen -W "${opts}" -- "${cur}"))
}

complete -o bashdefault -o default -o nospace -F _step_cli_bash_autocomplete step
